# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IDP_Cocoapod_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'IDP_Cocoapods', :path => "../IDP_Cocoapods/"
  # Pods for IDP_Cocoapod_Project

end
